# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: '82DK Agents'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g webpack webpack-cli --save-dev
    npm install
    npx webpack --config webpack.config.js

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: AzureWebApp@1
  inputs:
    azureSubscription: '82nd Dread Korps Siege Regiment (6739c46c-a7ab-491e-83a9-64cef64819f7)'
    appType: 'webAppLinux'
    appName: 'GazelleApi-Dev'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|10.1'
  displayName: 'npm install, run webpack'
